### ISSUE TITLE
Question: expected value of odoo_prod.url variable

### ISSUE THREAD

**Issue by nqb** [lefilament/ansible_role_odoo_docker#1]
Hello,

According to documentation and example inventory, it looks like `odoo_prod.url` should be an URL.

But if I look at templates used by this role, I see that `odoo_prod.url` is used as a Traefik Host() matcher.

According to [Traefik's documentation](https://doc.traefik.io/traefik/https/acme/#configuration-examples), it seems that a Host() matcher is a domain.

Could you confirm expected value of `odoo_prod.url` variable ?

Thanks a lot.

**Comment by remi-filament** [comment]
Thank you @nqb 
I have clarified it in all README and in ansible repo in host_vars/Template_xxx that you should use only sub.domain without https:// in front
Fixed in this repo with 7e7180c1ed38ab75b168f803b2fcc1bbaa65386d
