### ISSUE TITLE
fetch_repos and fetch_repos_addons used wrong python interpreter

### ISSUE THREAD

**Issue by nqb** [lefilament/ansible_role_odoo_docker#8]
Hello,

With `odoo_version: 12.0` defined in inventory, `fetch_repos` and `fetch_repos_addons` have following shebangs:

```
#!/usr/bin/env python
```

### Expected behavior

Shebangs should be:
```
#!/usr/bin/env python3
```
according to templates code.

I'm using Ansible 2.10.5. If I add extra quotes, it works.

I will open a PR.

**Comment by remi-filament** [comment]
Thanks, this should be fixed with your PR #9
